// Add Action Types Here

// Editors Action Types
export const ADD_EDITORS = "ADD_EDITORS";
export const EDITORS_LOADING = "EDITORS_LOADING";
export const EDITORS_FAILED = "EDITORS_FAILED";
export const SAVE_EDITOR_REQUEST = "SAVE_EDITOR_REQUEST";
export const SAVE_EDITOR_SUCCESS = "SAVE_EDITOR_SUCCESS";
export const EDITOR_FORM_STATE_RESET = "EDITOR_FORM_STATE_RESET";
export const SAVE_EDITOR_FAILURE = "SAVE_EDITOR_FAILURE";
export const UPDATE_EDITOR_REQUEST = "UPDATE_EDITOR_REQUEST";
export const UPDATE_EDITOR_SUCCESS = "UPDATE_EDITOR_SUCCESS";
export const UPDATE_EDITOR_FAILURE = "UPDATE_EDITOR_FAILURE";
export const CREATE_RATING_REQUEST = "CREATE_EDITOR_REQUEST";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILURE = "CREATE_RATING_FAILURE";
export const UPDATE_RATING_REQUEST = "UPDATE_EDITOR_REQUEST";
export const UPDATE_RATING_SUCCESS = "UPDATE_RATING_SUCCESS";
export const UPDATE_RATING_FAILURE = "UPDATE_RATING_FAILURE";
export const RATING_FORM_STATE_RESET = "RATING_FORM_STATE_RESET";

// Users Action Types
export const ADD_USERS = "ADD_USERS";
export const USERS_LOADING = "USERS_LOADING";
export const USERS_FAILED = "USERS_FAILED";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

// Authentication Action Types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
